export const poolRadRaces = {

    0: "Monster",
    1: "Dwarf",
    2: "Elf",
    3: "Gnome",
    4: "Half-elf",
    5: "Halfling",
    6: "Half-orc",
    7: "Human",

}

export const genders = {
    0: "Male",
    1: "Female"
}

export const poolRadStatusCodes = {
    0: "Okay",
    1: "Animated",
    2: "Tempgone",
    3: "Running",
    4: "Unconscious",
    5: "Dying",
    6: "Dead",
    7: "Stoned",
    8: "Gone",
    
}

export const alignments = {

    0: "Lawful Good",
    1: "Lawful Neutral",
    2: "Lawful Evil",
    3: "Neutral Good",
    4: "True Neutral",
    5: "Neutral Evil",
    6: "Chaotic Good",
    7: "Chaotic Neutral",
    8: "Chaotic Evil"
}

export const poolRadSpells ={

    51: {spellName: "Bless", class: "Cleric", level: 1},
    52: {spellName: "Curse", class: "Cleric", level: 1},
    53: {spellName: "Cure Light Wounds", class: "Cleric", level: 1},
    54: {spellName: "Cause Light Wounds", class: "Cleric", level: 1},
    55: {spellName: "Detect Magic", class: "Cleric", level: 1},
    56: {spellName: "Protection from Evil", class: "Cleric", level: 1},
    57: {spellName: "Protection from Good", class: "Cleric", level: 1},
    58: {spellName: "Resist Cold", class: "Cleric", level: 1},
    59: {spellName: "Burning Hands", class: "Mage", level: 1},
    60: {spellName: "Charm Person", class: "Mage", level: 1},
    61: {spellName: "Detect Magic", class: "Mage", level: 1},
    62: {spellName: "Enlarge", class: "Mage", level: 1},
    63: {spellName: "Reduce", class: "Mage", level: 1},
    64: {spellName: "Friends", class: "Mage", level: 1},
    65: {spellName: "Magic Missile", class: "Mage", level: 1},
    66: {spellName: "Protection from Evil", class: "Mage", level: 1},
    67: {spellName: "Protection from Good", class: "Mage", level: 1},
    68: {spellName: "Read Magic", class: "Mage", level: 1},
    69: {spellName: "Shield", class: "Mage", level: 1},
    70: {spellName: "Shocking Grasp", class: "Mage", level: 1},
    71: {spellName: "Sleep", class: "Mage", level: 1},
    72: {spellName: "Find Traps", class: "Cleric", level: 2},
    73: {spellName: "Hold Person", class: "Cleric", level: 2},
    74: {spellName: "Resist Fire", class: "Cleric", level: 2},
    75: {spellName: "Silence, 15' Radius", class: "Cleric", level: 2},
    76: {spellName: "Slow Poison", class: "Cleric", level: 2},
    77: {spellName: "Snake Charm", class: "Cleric", level: 2},
    78: {spellName: "Spiritual Hammer", class: "Cleric", level: 2},
    79: {spellName: "Detect Invisibility", class: "Mage", level: 3},
    80: {spellName: "Invisibility", class: "Mage", level: 3},
    81: {spellName: "Knock", class: "Mage", level: 3},
    82: {spellName: "Mirror Image", class: "Mage", level: 3},
    83: {spellName: "Ray of Enfeeblement", class: "Mage", level: 3},
    84: {spellName: "Stinking Cloud", class: "Mage", level: 3},
    85: {spellName: "Strength", class: "Mage", level: 3},
    86: {spellName: "Animate Dead", class: "Cleric", level: 3},
    87: {spellName: "Cure Blindness", class: "Cleric", level: 3},
    88: {spellName: "Cause Blindness", class: "Cleric", level: 3},
    89: {spellName: "Cure Disease", class: "Cleric", level: 3},
    90: {spellName: "Cause Disease", class: "Cleric", level: 3},
    91: {spellName: "Dispel Magic", class: "Cleric", level: 3},
    92: {spellName: "Prayer", class: "Cleric", level: 3},
    93: {spellName: "Remove Curse", class: "Cleric", level: 3},
    94: {spellName: "Bestow Curse", class: "Cleric", level: 3},
    95: {spellName: "Blink", class: "Mage", level: 3},
    96: {spellName: "Dispel Magic", class: "Mage", level: 3},
    97: {spellName: "Fireball", class: "Mage", level: 3},
    98: {spellName: "Haste", class: "Mage", level: 3},
    99: {spellName: "Hold Person", class: "Mage", level: 3},
    100: {spellName: "Inivisibility, 10' Radius", class: "Mage", level: 3},
    101: {spellName: "Lightning Bolt", class: "Mage", level: 3},
    102: {spellName: "Protection from Evil, 10' Radius", class: "Mage", level: 3},
    103: {spellName: "Protection from Good, 10' Radius", class: "Mage", level: 3},
    104: {spellName: "Protection from Normal Missiles", class: "Mage", level: 3},
    105: {spellName: "Slow", class: "Mage", level: 3},
    106: {spellName: "Restoration", class: "Cleric", level: 7},
}

export const poolRadItemValues = {

    0: "",
    1: "Battle Axe",
    2: "Hand Axe",
    3: "Bardiche",
    4: "Bec de Corbin",
    5: "Bill Guisarme",
    6: "Bo Staff",
    7: "Club",
    8: "Dagger",
    9: "Dart",
    10: "Fauchard",
    11: "Fauchard-Fork",
    12: "Flail",
    13: "Military Fork",
    14: "Glaive",
    15: "Glaive-Guisarme",
    16: "Guisarme",
    17: "Guisarme-Voulge",
    18: "Halberd",
    19: "Lucern Hammer",
    20: "Hammer",
    21: "Javelin",
    22: "Jo Stick",
    23: "Mace",
    24: "Morning Star",
    25: "Partisan",
    26: "Military Pick",
    27: "Awl Pike",
    28: "Quarrel",
    29: "Ranseur",
    30: "Scimitar",
    31: "Spear",
    32: "Spetum",
    33: "Quarter Staff",
    34: "Bastard Sword",
    35: "Broad Sword",
    36: "Long Sword",
    37: "Short Sword",
    38: "Two-handed Sword",
    39: "Trident",
    40: "Voulge",
    41: "Composite Long Bow",
    42: "Composite Short Bow",
    43: "Long Bow",
    44: "Short Bow",
    45: "Heavy Crossbow",
    46: "Light Crossbow",
    47: "Sling",
    48: "Mail",
    49: "Armor",
    50: "Leather",
    51: "Padded",
    52: "Studded",
    53: "Ring",
    54: "Scale",
    55: "Chain",
    56: "Splint",
    57: "Banded",
    58: "Plate",
    59: "Shield",
    60: "Woods",
    61: "Elven Chain",
    62: "Ice Storm",
    63: "Sapphire",
    64: "Emerald",
    65: "Wizardry",
    66: "Hornet's Nest",
    67: "Fire Resistance",
    68: "Stone",
    69: "Good Luck",
    70: "Flail",
    71: "Halberd",
    72: "Gauntlets",
    78: "Ogre Power",
    79: "Girdle",
    80: "Giant Strength",
    81: "Mirror",
    82: "Necklace",
    83: "Dragon",
    84: "Vs Giants",
    85: "85",
    86: "86",
    87: "Diamond",
    88: "Lightning",
    89: "Fireballs",
    90: "of",
    91: "Vulnerability",
    92: "Speed",
    93: "Silver",
    94: "Extra",
    95: "Healing",
    96: "Charming",
    97: "Fear",
    98: "Magic Missiles",
    99: "Missiles",
    100: "1 Spell",
    101: "2 Spells",
    102: "3 Spells",
    103: "Paralyzation",
    104: "Invisibility",
    105: "Cute Yellow Canary",
    106: "AC 10",
    107: "AC 6",
    108: "AC 4",
    109: "AC 3",
    110: "AC 2",
    111: "+1",
    112: "+2",
    113: "+3",
    114: "+4",
    115: "+5",
    116: "-1",
    117: "-2",
    118: "-3",
    121: "Spiritual",
    122: "Gem",
    123: "Jewelry",


}